language: java
install: mvn install -Dgpg.skip=true -Dmaven.javadoc.skip=true

# JDK 8 and 11 both support compiling with -source 1.6 -target 1.6.
# JDK 17+ dropped support for source/target 1.6.
jdk:
  - openjdk8
  - openjdk11

env:
  global:
    # COVERITY_SCAN_TOKEN (encrypted)
    - secure: "uYhystsHudliu0dhn//lI5jGUs58Ng3eJ9GZbUtajVor0RtIjpmE2MnUjkvGR6vB6bBpErbiC5imWwfLwX9a+JT51KAOvUf7HQv2/WO7voMx2oZ1d9ahhq3S6hRkBnNKWJDTe1MjS9D2fr/y0uknuShgQ4t5FYBIQTqHEl30ssQ="

addons:
  coverity_scan:
    project:
      name: "bernardladenthin/streambuffer"
      description: "Build submitted via Travis CI"
    notification_email: bernard.ladenthin@gmail.com
    build_command_prepend: "mvn clean"
    build_command: "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan

after_success:
  - bash <(curl -s https://codecov.io/bash)
